class AppStrings {
  static const noSkills = 'No Skills..!';
  static const categoriesContent = 'Your health is our priority..!';
  static const loginContentText = 'Appoint Your Doctor Easily';
  static const email = 'Email';
  static const password = 'Password';
  static const forgotPassword = 'Forgot Password';
  static const signIn = 'Sign In';
  static const continueWith = 'Or Continue with';
  static const signUp = 'Sign Up';
  static const forgotPasswordContent =
      'Enter the phone number associated with your account';
  static const getOtp = 'Get Otp';
  static const signUpContentText = 'Enter your details to get started';
  static const firstName = 'First Name';
  static const lastName = 'Last Name';
  static const dateOfBirth = 'Date of Birth';
  static const male = 'Male';
  static const female = 'Female';
  static const verificationContent =
      'Enter the OTP sent to your phone number associated with your account';
  static const verifyProceed = 'Verify & Proceed';
  static const findYourDoctor = 'Find Your Doctor';
  static const noDoctors = 'No Doctors..!';
  static const qualification = 'Qualification';
  static const specialties = 'Specialties';
  static const awards = 'Awards';
  static const about = 'About';
  static const makeAppointment = 'Make Appointment';
  static const slots = 'Slots';
  static const visit = 'Have you visited before?';
  static const bookAppointment = 'Book Appointment';
  static const reasonToVisit = 'Reason to visit doctor?';
  static const noSlotsAvailable = 'No Slots Available';
  static const onGoing = 'On-Going';
  static const missed = 'Missed';
  static const completed = 'Completed';
  static const noAppointments = 'No Appointments..!';
  static const cancel = 'Cancel';
  static const reSchedule = 'Re-Schedule';
  static const reScheduleAppointment = 'Re-Schedule Appointment';
  static const specialization = 'Specialization';
  static const cityState = 'City / State';
  static const search = 'Search';
  static const profile = 'Profile';
  static const userName = 'User Name';
  static const insurance = 'Insurances';
  static const deleteAccount = 'Delete Account?';
  static const noInsurances = 'No Insurances..!';
  static const addInsurances = 'Add Insurance';
  static const insuranceDetails = 'Insurance Details';
  static const frontSideDocument = 'Front Side Document';
  static const backSideDocument = 'Back Side Document';
  static const title = 'Title';
  static const searchInsurances = 'Search Insurances';
  static const view = 'View';
  static const isActive = 'is Active';
  static const addInsurance = 'Add Insurance';

  static const reSendOtp = 'Re-send OTP';
  static const changePassword = 'Change Password';
  static const changePasswordContentText =
      'Create a new password that is strong and secure.';
  static const confirmPassword = 'Confirm Password';
  static const confirm = 'Confirm';
  static const reEnterPassword = 'Re-enter your Password';
  static const phoneNumber = 'Phone Number';
  static const passwordNotMatch = 'Password doesn\'t match';
}
