name: drs_booking
description: "Doctor Booking App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  persistent_bottom_nav_bar: ^6.2.1
  http: ^1.3.0
  lottie: ^3.1.3
  provider: ^6.1.2
  toastification: ^2.3.0
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.2
  shared_preferences: ^2.4.0
  table_calendar: ^3.2.0
  intl: ^0.20.2
  dropdown_search: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: MetrischSemiBold
      fonts:
        - asset: assets/fonts/metrisch_bold.otf

    - family: MetrischRegular
      fonts:
        - asset: assets/fonts/metrisch_medium.otf

  assets:
    - assets/loader/loading.json
    - assets/loader/profile.json
    - assets/noData/noData.json
    - assets/icons/bottom_home_menu.png
    - assets/icons/bottom_search_menu.png
    - assets/icons/bottom_appointments_menu.png
    - assets/icons/bottom_profile_menu.png
    - assets/images/categories_header_background.png
    - assets/images/app_logo.png
    - assets/images/login_background.png
    - assets/images/google.png
    - assets/images/forgot_password_vector.png
    - assets/images/doctor_icon_logo.png
    - assets/images/log_out.png
    - assets/images/dummy_image.jpg
    - assets/images/close_image.png
