name: drs_booking
description: "Doctor Booking App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  persistent_bottom_nav_bar: ^6.2.1
  http: ^1.3.0
  lottie: ^3.1.3
  provider: ^6.1.2
  toastification: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: MetrischSemiBold
      fonts:
        - asset: assets/fonts/metrisch_bold.otf

    - family: MetrischRegular
      fonts:
        - asset: assets/fonts/metrisch_medium.otf

  assets:
    - assets/icons/bottom_home_menu.png
    - assets/icons/bottom_search_menu.png
    - assets/icons/bottom_appointments_menu.png
    - assets/icons/bottom_profile_menu.png
    - assets/images/categories_header_background.png
